### PR TITLE
Json control character escaping

### PR DESCRIPTION
**Pull request by sjasperse**
Escaping the '\' and '"' characters.

### CODE REVIEW

**Comment by sjasperse** [comment]
@zoranmax I know this is a pretty inactive repo, but I still use the nuget package, and ran into an issue recently in prod. :-)
I've added pretty thorough unit testing to try to make the PR pretty easy. Let me know if you have any questions.

**Comment by zoranmax** [comment]
Hi,
I am fine to integrate this one, but looking at the code it looks like that this could be potentially a breaking change, as some people might have implemented this quoting logic already somewhere... I am honestly just worried about this one. Perhaps a flag could be placed somewhere to disable it by default? What do you think?

**Comment by sjasperse** [comment]
That's a good suggestion. I'll include that.

**Comment by sjasperse** [comment]
Updated. I didn't add testing for the negative side (non-escaping) since the code was pretty straightforward, but let me know if that makes you uncomfortable.

Added a custom escaping callback also, since the escaping I included is pretty limited.

**Comment by sjasperse** [comment]
@zoranmax - could I trouble you to review this soon? Sorry to bother you.

**Comment by zoranmax** [comment]
Hi,

I just published the nuget package
https://www.nuget.org/packages/Google.DataTable.Net.Wrapper/4.1.

I'm really sorry that it took me some time :-)  Thank you very much for your support+

**Comment by sjasperse** [comment]
No problem! Been pretty busy myself, so I know how it goes.

**Pull request merged**
